name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

# wrangler.toml (wrangler v3.79.0^)
[observability]
enabled = true
head_sampling_rate = 1

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = "ai101.cc"

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"

[env.production]
name = "cloudflare-docker-proxy"
 routes = [
   { pattern = "docker.ai101.cc", custom_domain = true },
   { pattern = "quay.ai101.cc", custom_domain = true },
   { pattern = "gcr.ai101.cc", custom_domain = true },
   { pattern = "k8s-gcr.ai101.cc", custom_domain = true },
   { pattern = "k8s.ai101.cc", custom_domain = true },
   { pattern = "ghcr.ai101.cc", custom_domain = true },
   { pattern = "cloudsmith.ai101.cc", custom_domain = true },
 ]

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = "https://k8s.gcr.io"

[env.staging]
name = "cloudflare-docker-proxy-staging"
# route = { pattern = "docker-staging.libcuda.so", custom_domain = true }

[env.staging.vars]
MODE = "staging"
TARGET_UPSTREAM = ""
